name: Deploy static content to Pages

on:
  # Trigger el despliegue cuando se haga push al branch gh-pages
  push:
    branches: ["gh-pages"]
  
  # Permite ejecutar este flujo manualmente desde la pestaña de Actions
  workflow_dispatch:

# Permisos para interactuar con GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Configuración para que solo se ejecute una instancia del despliegue a la vez
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # Paso 2: Subir los archivos de la carpeta de build (ajusta la ruta según tus necesidades)
      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './build'  # Cambia esta ruta si los archivos generados están en otro directorio

      # Paso 3: Desplegar los archivos estáticos a GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
